class Solution:
    def furthestBuilding(self, heights: List[int], bricks: int, ladders: int) -> int:
        
        # print(f"heights: {heights}, bricks: {bricks}, ladders: {ladders}")
        # print(f"heights[0]: {heights[0]}")
        # print(f"heights[1]: {heights[1]}")
        # print(f"heights[2]: {heights[2]}")
        # print(f"heights[3]: {heights[3]}")
        # print(f"heights[4]: {heights[4]}")
        # print(f"heights[5]: {heights[5]}")
        # print(f"heights[6]: {heights[6]}")
        # print(f"heights[7]: {heights[7]}")
        # print(f"heights[8]: {heights[8]}")
        # print(f"heights[9]: {heights[9]}")
        # print(f"heights[10]: {heights[10]}")
        # print(f"heights[11]: {heights[11]}")
        # print(f"heights[12]: {heights[12]}")
        # print(f"heights[13]: {heights[13]}")
        # print(f"heights[14]: {heights[14]}")
        # print(f"heights[15]: {heights[15]}")
        # print(f"heights[16]: {heights[16]}")
        # print(f"heights[17]: {heights[17]}")
        # print(f"heights[18]: {heights[18]}")
        # print(f"heights[19]: {heights[19]}")
        # print(f"heights[20]: {heights[20]}")
        # print(f"heights[21]: {heights[21]}")
        # print(f"heights[22]: {heights[22]}")
        # print(f"heights[23]: {heights[23]}")
        # print(f"heights[24]: {heights[24]}")
        # print(f"heights[25]: {heights[25]}")
        # print(f"heights[26]: {heights[26]}")
        # print(f"heights[27]: {heights[27