class Solution:
    def restoreArray(self, adjacentPairs: List[List[int]]) -> List[int]:
        
        # 1. Find the first element
        # 2. Find the second element
        # 3. Find the third element
        # 4. Find the fourth element
        # 5. Find the fifth element
        # 6. Find the sixth element
        # 7. Find the seventh element
        # 8. Find the eighth element
        # 9. Find the ninth element
        # 10. Find the tenth element
        # 11. Find the eleventh element
        # 12. Find the twelfth element
        # 13. Find the thirteenth element
        # 14. Find the fourteenth element
        # 15. Find the fifteenth element
        # 16. Find the sixteenth element
        # 17. Find the seventeenth element
        # 18. Find the eighteenth element
        # 19. Find the nineteenth element
        # 20. Find the twentieth element
        # 21. Find the twenty-first element
        # 22. Find the twenty-second element
        # 23. Find the twenty-third element
        # 24. Find the twenty-fourth element
        # 25. Find the twenty-fifth element
        # 26. Find the twenty-sixth element
        # 27. Find the twenty-seventh element
        # 28. Find the twenty-eighth element
        # 29. Find the twenty-ninth element
        # 30. Find the thirtieth element
        # 31. Find the thirty-first element
        # 32. Find the thirty-second element
        # 33. Find the thirty-third element
        # 34. Find the thirty-fourth element
        # 35. Find the thirty-fifth element
        # 36. Find the thirty-sixth element
        # 37. Find the thirty-seventh element
        # 38. Find the thirty-eighth element
        # 39. Find the thirty-ninth element
        # 40. Find the fortieth element
        # 41. Find the forty-first element
        # 42. Find the forty-second element
        # 43. Find the forty-third element
        # 44. Find the forty-fourth element
        # 45. Find the forty-fifth