class Solution:
    def sumEvenAfterQueries(self, nums: List[int], queries: List[List[int]]) -> List[int]:
        
        # print("nums: ", nums)
        # print("queries: ", queries)
        # print("len(queries): ", len(queries))
        # print("len(nums): ", len(nums))
        # print("queries[0][0]: ", queries[0][0])
        # print("queries[0][1]: ", queries[0][1])
        # print("nums[0]: ", nums[0])
        # print("nums[1]: ", nums[1])
        # print("nums[2]: ", nums[2])
        # print("nums[3]: ", nums[3])
        # print("nums[4]: ", nums[4])
        # print("nums[5]: ", nums[5])
        # print("nums[6]: ", nums[6])
        # print("nums[7]: ", nums[7])
        # print("nums[8]: ", nums[8])
        # print("nums[9]: ", nums[9])
        # print("nums[10]: ", nums[10])
        # print("nums[11]: ", nums[11])
        # print("nums[12]: ", nums[12])
        # print("nums[13]: ", nums[13])
        # print("nums[14]: ", nums[14])
        # print("nums[15]: ", nums[15])
        # print("nums[16]: ", nums[16])
        # print("nums[17]: ", nums[17])
        # print("nums[18]: ", nums[18])
        # print("nums[19]: ", nums[19])
        # print("nums[20]: ", nums[20])
        # print("nums[21]: ", nums[21])
        # print("nums[22]: ", nums[22])
        # print("nums[23]: ", nums[23])
        # print("nums[24]: ", nums[24])
        # print("nums[25]: ", nums[25])
        # print("nums[26]: ", nums[26])
        # print("nums[27]: ", nums[27])
        # print("nums[28]: ", nums[28])
        # print("nums[29]: ", nums[29])
        # print("nums[30]: ", nums[30])
        # print("nums[31]: ", nums[31])
        # print("nums[32