class Solution:
    def uniquePaths(self, m: int, n: int) -> int:
        
        # 1. recursive solution
        # 2. DP solution
        # 3. math solution
        # 4. combinatorics solution
        # 5. binary solution
        # 6. matrix solution
        # 7. combinatorics solution
        # 8. combinatorics solution
        # 9. combinatorics solution
        # 10. combinatorics solution
        # 11. combinatorics solution
        # 12. combinatorics solution
        # 13. combinatorics solution
        # 14. combinatorics solution
        # 15. combinatorics solution
        # 16. combinatorics solution
        # 17. combinatorics solution
        # 18. combinatorics solution
        # 19. combinatorics solution
        # 20. combinatorics solution
        # 21. combinatorics solution
        # 22. combinatorics solution
        # 23. combinatorics solution
        # 24. combinatorics solution
        # 25. combinatorics solution
        # 26. combinatorics solution
        # 27. combinatorics solution
        # 28. combinatorics solution
        # 29. combinatorics solution
        # 30. combinatorics solution
        # 31. combinatorics solution
        # 32. combinatorics solution
        # 33. combinatorics solution
        # 34. combinatorics solution
        # 35. combinatorics solution
        # 36. combinatorics solution
        # 37. combinatorics solution
        # 38. combinatorics solution
        # 39. combinatorics solution
        # 40. combinatorics solution
        # 41. combinatorics solution
        # 42. combinatorics solution
        # 43. combinatorics solution
        # 44. combinatorics solution
        # 45. combinatorics solution
        # 46. combinatorics solution
        # 47. combinatorics solution
        # 48. combinatorics solution
        # 49. combinatorics solution
        # 50. combinatorics solution
        # 51. combinatorics solution