class Solution:
    def numDifferentIntegers(self, word: str) -> int:
        
        word = word.replace(" ","0")
        word = word.replace("a"," ")
        word = word.replace("b"," ")
        word = word.replace("c"," ")
        word = word.replace("d"," ")
        word = word.replace("e"," ")
        word = word.replace("f"," ")
        word = word.replace("g"," ")
        word = word.replace("h"," ")
        word = word.replace("i"," ")
        word = word.replace("j"," ")
        word = word.replace("k"," ")
        word = word.replace("l"," ")
        word = word.replace("m"," ")
        word = word.replace("n"," ")
        word = word.replace("o"," ")
        word = word.replace("p"," ")
        word = word.replace("q"," ")
        word = word.replace("r"," ")
        word = word.replace("s"," ")
        word = word.replace("t"," ")
        word = word.replace("u"," ")
        word = word.replace("v"," ")
        word = word.replace("w"," ")
        word = word.replace("x"," ")
        word = word.replace("y"," ")
        word = word.replace("z"," ")
        word = word.replace(" ","")
        word = word.replace("0"," ")
        word = word.strip()
        word = word.split(" ")
        word = list(set(word))
        return len(word)