impl Solution {
    pub fn min_flips(s: String) -> i32 {
        
        let mut s = s;
        let mut s1 = s.clone();
        let mut s2 = s.clone();
        let mut s3 = s.clone();
        let mut s4 = s.clone();
        let mut s5 = s.clone();
        let mut s6 = s.clone();
        let mut s7 = s.clone();
        let mut s8 = s.clone();
        let mut s9 = s.clone();
        let mut s10 = s.clone();
        let mut s11 = s.clone();
        let mut s12 = s.clone();
        let mut s13 = s.clone();
        let mut s14 = s.clone();
        let mut s15 = s.clone();
        let mut s16 = s.clone();
        let mut s17 = s.clone();
        let mut s18 = s.clone();
        let mut s19 = s.clone();
        let mut s20 = s.clone();
        let mut s21 = s.clone();
        let mut s22 = s.clone();
        let mut s23 = s.clone();
        let mut s24 = s.clone();
        let mut s25 = s.clone();
        let mut s26 = s.clone();
        let mut s27 = s.clone();
        let mut s28 = s.clone();
        let mut s29 = s.clone();
        let mut s30 = s.clone();
        let mut s31 = s.clone();
        let mut s32 = s.clone();
        let mut s33 = s.clone();
        let mut s34 = s.clone();
        let mut s35 = s.clone();
        let mut s36 = s.clone();
        let mut s37 = s.clone();
        let mut s38 = s.clone();
        let mut s39 = s.clone();
        let mut s40 = s.clone();
        let mut s41 = s.clone();
        let mut s42 = s.clone();
        let mut s43 = s.clone();
        let mut s44 = s.clone();
        let mut s45 = s.clone();
        let mut s46 = s.clone();
        let mut s47 = s.clone();
        let mut s48 = s.clone();
        let mut s49 = s.clone();
        let mut s50 = s.clone();
        let mut s51 = s.clone();
        let mut s52 = s.clone();
        let mut s53 = s.clone();
        let mut s54 = s.clone();
        let mut s55 =
    }
}