class Solution:
    def fallingSquares(self, positions: List[List[int]]) -> List[int]:
        
        # print(positions)
        # print(len(positions))
        # print(positions[0][0])
        # print(positions[0][1])
        # print(positions[0][0]+positions[0][1])
        # print(positions[1][0])
        # print(positions[1][1])
        # print(positions[1][0]+positions[1][1])
        # print(positions[2][0])
        # print(positions[2][1])
        # print(positions[2][0]+positions[2][1])
        # print(positions[3][0])
        # print(positions[3][1])
        # print(positions[3][0]+positions[3][1])
        # print(positions[4][0])
        # print(positions[4][1])
        # print(positions[4][0]+positions[4][1])

        # print(positions[0][0]<positions[1][0])
        # print(positions[0][0]+positions[0][1]>positions[1][0])
        # print(positions[0][0]<positions[1][0]+positions[1][1])
        # print(positions[0][0]+positions[0][1]>positions[1][0]+positions[1][1])
        # print(positions[0][0]<positions[2][0])
        # print(positions[0][0]+positions[0][1]>positions[2][0])
        # print(positions[0][0]<positions[2][0]+positions[2][1])
        # print(positions[0][0]+positions[0][1]>positions[2][0]+positions[2][1])
        # print(positions[0][0]<positions[3][0])
        # print(positions[0][0]+positions[0][1]>positions[3][0])
        # print(positions[0][0]<positions[3][0]+positions[3][1])
        # print(positions[0][0]+positions[0][1]>positions[3][0]+positions[3][1])
        # print(positions[0][0]<positions[4][0])
        # print(positions[0][0]+positions[0][1]>positions[4][0])
        # print(position