class Solution:
    def isMatch(self, s: str, p: str) -> bool:
        
        # s = "aa", p = "a"
        # s = "aa", p = "*"
        # s = "cb", p = "?a"
        # s = "adceb", p = "*a*b"
        # s = "acdcb", p = "a*c?b"
        # s = "abefcdgiescdfimde", p = "ab*cd?i*de"
        # s = "ho", p = "**ho"
        # s = "ho", p = "ho**"
        # s = "ho", p = "**ho**"
        # s = "ho", p = "*ho**"
        # s = "ho", p = "**ho*"
        # s = "ho", p = "ho*"
        # s = "ho", p = "*ho"
        # s = "ho", p = "h*o"
        # s = "ho", p = "*h*o*"
        # s = "ho", p = "*h*o"
        # s = "ho", p = "h*o*"
        # s = "ho", p = "h*o"
        # s = "ho", p = "h**"
        # s = "ho", p = "**h"
        # s = "ho", p = "h**o"
        # s = "ho", p = "h*o*"
        # s = "ho", p = "h*o"
        # s = "ho", p = "h**"
        # s = "ho", p = "**h"
        # s = "ho", p = "h**o"
        # s = "ho", p = "h*o*"
        # s = "ho", p = "h*o"
        # s = "ho", p = "h**"
        # s = "ho", p = "**h"
        # s = "ho", p = "h**o"
        # s = "ho", p = "h*o*"
        # s = "ho", p = "h*o"
        # s = "ho", p = "h**"
        # s = "ho", p = "**h"
        # s = "ho", p = "h**o"
        # s = "ho