class Solution:
    def isPathCrossing(self, path: str) -> bool:
        
        # path = "NES"
        # path = "NESWW"
        # path = "N"
        # path = "NN"
        # path = "NNN"
        # path = "NNNN"
        # path = "NNNNN"
        # path = "NNNNNN"
        # path = "NNNNNNN"
        # path = "NNNNNNNN"
        # path = "NNNNNNNNN"
        # path = "NNNNNNNNNN"
        # path = "NNNNNNNNNNN"
        # path = "NNNNNNNNNNNN"
        # path = "NNNNNNNNNNNNN"
        # path = "NNNNNNNNNNNNNN"
        # path = "NNNNNNNNNNNNNNN"
        # path = "NNNNNNNNNNNNNNNN"
        # path = "NNNNNNNNNNNNNNNNN"
        # path = "NNNNNNNNNNNNNNNNNN"
        # path = "NNNNNNNNNNNNNNNNNNN"